### ISSUE TITLE
See what is common with my functionMap2

### ISSUE THREAD

**Issue by gaborcsardi** [krlmlr/rapier#5]
and if we can have a common core.

https://github.com/gaborcsardi/functionMap2

**Comment by gaborcsardi** [comment]
As I see after a very quick look:
* `functionMap2` does more: it extracts function call positions, function definition positions.
* `rapier` does more: extracts API, that's the point after all.
* `rapier` does more: handles S3 functions better AFAICT
* `functionMap2` loads the package in another R session, so the current session is kept clean.
* `functionMap2` only cares about functions, currently.

**Comment by krlmlr** [comment]
That's what I see, too. We might be able to find a data structure that accommodates both needs (#4). I do like my package name better, though ;-)

**Comment by gaborcsardi** [comment]
>  We might be able to find a data structure that accommodates both needs 

Would be great! I definitely want to extract the API as well. I also want a function that exports the whole thing in JSON, but that is easy, essentially one function call...

> I do like my package name better, though ;-)

Yes, no question about that. :)

**Comment by gaborcsardi** [comment]
So if you want to merge, we can also move the package to `r-pkgs`, I suppose.

**Comment by krlmlr** [comment]
Sure, fine with merging and moving to r-pkgs. No need to rush, though; I just wanted something working fast before the upcoming tibble release.

**Comment by gaborcsardi** [comment]
Cool!

**Comment by krlmlr** [comment]
Merging probably means we tweak your code for support of S3 functions and I add print() and format() methods.

**Comment by gaborcsardi** [comment]
Well, and the API extraction as well. 

But I can help, too.

And I did not put a lot of effort into coming up with the functionmap2 name. :) So I don't mind changing it, but how about sg more descriptive, e.g. `pkgapi`?

Anyway, I'll move over the package and add you.

**Comment by krlmlr** [comment]
Yeah, a rapier is used more for stabbing than for cutting... `pkgapi` is fine for now.

**Comment by krlmlr** [comment]
Done merging, renamed prepare_package() to extract_api().

**Comment by gaborcsardi** [comment]
Thanks!
